openapi: "3.0.0"
info:
  title: TODO-API document
  version: "0.0.1"
  description: TODO-API document
tags:
  - name: opts
    description: 運用監視API
  - name: tasks
    description: タスク関連API
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /tasks/:
    post:
      summary: "Create new task"
      description: "Create new task item"
      operationId: createTask
      tags:
        - tasks
      responses:
        201:
          description: "Created"
  /tasks/{taskId}:
    get:
      tags:
        - tasks
      # operationId = TasksApi I/Fのメソッド名
      operationId: showTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: "Target task ID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
        '404':
          description: "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundError"
components:
  schemas:
    TaskDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "Task ID"
        title:
          type: string
          description: "Task title"
      required:
        - id
        - title
    ResourceNotFoundError:
      description: "Specified resource does not exist"
      type: object
      properties:
        title:
          type: string
          description: "Error title"
          default: "Resource Not found"
        detail:
          type: string
          default: "Error details"
      required:
        - title
        - detail