openapi: "3.0.0"
info:
  title: TODO-API document
  version: "0.0.1"
  description: TODO-API document
tags:
  - name: opts
    description: 運用監視API
  - name: tasks
    description: タスク関連API
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /tasks/1:
    get:
      tags:
        - tasks
      # operationId = TasksApi I/Fのメソッド名
      operationId: showTask
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
components:
  schemas:
    TaskDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "Task ID"
        title:
          type: string
          description: "Task title"
      required:
        - id
        - title