openapi: "3.0.0"
info:
  title: TODO-API document
  version: "0.0.1"
  description: TODO-API document
tags:
  - name: opts
    description: 運用監視API
  - name: tasks
    description: タスク関連API
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /tasks/1:
    get:
      tags:
        - tasks
      # operationId = TasksApi I/Fのメソッド名
      operationId: showTask
      responses:
        '200':
          description: OK